export const CREATE_PORTFOLIO = "CREATE_PORTFOLIO";
export const RETRIEVE_PORTFOLIOS = "RETRIEVE_PORTFOLIOS";
export const UPDATE_PORTFOLIO = "UPDATE_PORTFOLIO";
export const DELETE_PORTFOLIO = "DELETE_PORTFOLIO";
export const DELETE_ALL_PORTFOLIOS = "DELETE_ALL_PORTFOLIOS";